version: '3.7'

services:
#    db:
#        container_name: gogqlserver_mysql
#        image: mysql:8.0.18
#        restart: unless-stopped
#        command: ["--default-authentication-plugin=mysql_native_password"]
#        healthcheck:
#            test: "exit 0"
#        environment:
#            MYSQL_ROOT_PASSWORD: uKacNYFqFqbjU0aD8Vw0rvEF1V27B6wM
#            MYSQL_DATABASE: gogqlserver
#            MYSQL_USER: dummy
#            MYSQL_PASSWORD: uKacNYFqFqbjU0aD8Vw0rvEF1V27B6wM
#        volumes:
#            - ./docker/mysql:/etc/mysql/conf.d
#        ports:
#            - "3306:3306"

    mongo1:
        hostname: mongo1
        container_name: gogqlserver_mongo1
        image: mongo:4.2.2-bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: uKacNYFqFqbjU0aD8Vw0rvEF1V27B6wM
        expose:
            - 27017
        ports:
            - 27017:27017
        volumes:
            - ./docker/mongo:/data/db
        restart: unless-stopped
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
        
    mongo2:
        hostname: mongo2
        container_name: gogqlserver_mongo2
        image: mongo:4.2.2-bionic
        expose:
            - 27017
        ports:
            - 27018:27017
        restart: unless-stopped
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
        
    mongo3:
        hostname: mongo3
        container_name: gogqlserver_mongo3
        image: mongo:4.2.2-bionic
        expose:
            - 27017
        ports:
            - 27019:27017
        restart: unless-stopped
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

    mongo-express:
        container_name: gogqlserver_mongo_express
        image: mongo-express:0.49.0
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: 'mongo1,mongo2,mongo3'
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: uKacNYFqFqbjU0aD8Vw0rvEF1V27B6wM
        depends_on:
          - mongo1
          - mongo2
          - mongo3

#    app:
#        container_name: gogqlserver_app
#        build:
#          context: ./
#          dockerfile: ./docker/app/dev.Dockerfile
#        restart: unless-stopped
#        env_file:
#            - .env
#        depends_on:
#          - db
#        ports:
#        - "7777:7777"
